import os
import time
def anamenu():
    print("---------------------PROGRAMA HOŞGELDİNİZ---------------------")
    print("-Decimal to Binary hesaplaması için '1' yazınız...")
    print("-Subnet hesaplaması için '2' yazınız...")
    secim = input("-Seçiniz:")
    os.system("cls")
    if secim == "1":
        decimal()
    elif secim == "2":
        subnet()
    elif secim == "exit" or "EXIT":
        os.system("exit")
    else:
        print("Yanlış değer girdiniz, lütfen bekleyiniz...")
        time.sleep(1.5)
        os.system("cls")
        return anamenu()

def decimal():
    while True:
        print("---------------------DECIMAL TO BINARY DÖNÜŞTÜME---------------------")
        print("'1'ile'255' arası sayı giriniz.")
        try:
            a = int(input("Sayı Giriniz:"))
        except ValueError:
            os.system("cls")
            return decimal()
        bnr = bin(a).replace('0b','')
        x = bnr[::-1]
        while len(x) < 8:
            x += '0'
        bnr = x[::-1]
        print(bnr) 
        print("")
        next = input("Yeniden hesaplamak için enter'a basınız, Anamenüye dönmek için 'back', çıkmak için 'exit' yazınız.:")
        os.system("cls")
        if next == "":
            continue
        elif next == "back":
            anamenu()
        else:
            break
def subnet():
    while True:
        print("---------------------SUBNET HESAPLAMA---------------------")
        print("Not: Program 1,2,4,8,16 seçeneklerine bölüm yapabilir.")
        print("--------------------------")
        print("Örnek Kullanım: \n Network Id: 192.168.1. \n Subnet Mask: 255.255.255. \n Subnet Sayısı: 2" )
        print("--------------------------")
        networkid = str(input("Network Id Giriniz:"))
        subnet = str(input("Subnet Mask Giriniz:"))
        bolum = (input("Kaç Subnete Bölünecek:"))

        if bolum == "1":
            print("_________________________________________________________________________________")
            print("--------Network 1--------")
            print("Network id:",networkid,"0",sep="")
            print("Gateway:",networkid,"1",sep="")
            print("Broadcast:",networkid,"255",sep="")
            print("Subnet Mask:",subnet,"0",sep="")
            print("Kullanılabilir ip'ler:",networkid,"1"," - ",networkid,"254",sep="")
            print("_________________________________________________________________________________")

        elif bolum == "2":
            print("_________________________________________________________________________________")
            print("--------Network 1--------")
            print("Network id:",networkid,"0",sep="")
            print("Gateway:",networkid,"1",sep="")
            print("Broadcast:",networkid,"127",sep="")
            print("Subnet Mask:",subnet,"128",sep="")
            print("Kullanılabilir ip'ler:",networkid,"1"," - ",networkid,"126",sep="")
            print("--------Network 2--------")
            print("Network id:",networkid,"128",sep="")
            print("Gateway:",networkid,"129",sep="")
            print("Broadcast:",networkid,"255",sep="")
            print("Subnet Mask:",subnet,"128",sep="")
            print("Kullanılabilir ip'ler:",networkid,"129"," - ",networkid,"254",sep="")
            print("_________________________________________________________________________________")
            
        elif bolum == "4": 
            print("_________________________________________________________________________________")
            print("--------Network 1--------")
            print("Network id:",networkid,"0",sep="")
            print("Gateway:",networkid,"1",sep="")
            print("Broadcast:",networkid,"63",sep="")
            print("Subnet Mask:",subnet,"192",sep="")
            print("Kullanılabilir ip'ler:",networkid,"1"," - ",networkid,"62",sep="")
            print("--------Network 2--------")
            print("Network id:",networkid,"64",sep="")
            print("Gateway:",networkid,"65",sep="")
            print("Broadcast:",networkid,"127",sep="")
            print("Subnet Mask:",subnet,"192",sep="")
            print("Kullanılabilir ip'ler:",networkid,"65"," - ",networkid,"126",sep="")
            print("--------Network 3--------")
            print("Network id:",networkid,"128",sep="")
            print("Gateway:",networkid,"129",sep="")
            print("Broadcast:",networkid,"191",sep="")
            print("Subnet Mask:",subnet,"192",sep="")
            print("Kullanılabilir ip'ler:",networkid,"129"," - ",networkid,"190",sep="")
            print("--------Network 4--------")
            print("Network id:",networkid,"192",sep="")
            print("Gateway:",networkid,"193",sep="")
            print("Broadcast:",networkid,"255",sep="")
            print("Subnet Mask:",subnet,"192",sep="")
            print("Kullanılabilir ip'ler:",networkid,"193"," - ",networkid,"254",sep="")
            print("_________________________________________________________________________________")

        elif bolum == "8": 
            print("_________________________________________________________________________________")
            print("--------Network 1--------")
            print("Network id:",networkid,"0",sep="")
            print("Gateway:",networkid,"1",sep="")
            print("Broadcast:",networkid,"31",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"1"," - ",networkid,"30",sep="")
            print("--------Network 2--------")
            print("Network id:",networkid,"32",sep="")
            print("Gateway:",networkid,"33",sep="")
            print("Broadcast:",networkid,"63",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"33"," - ",networkid,"62",sep="")
            print("--------Network 3--------")
            print("Network id:",networkid,"64",sep="")
            print("Gateway:",networkid,"65",sep="")
            print("Broadcast:",networkid,"95",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"65"," - ",networkid,"94",sep="")
            print("--------Network 4--------")
            print("Network id:",networkid,"96",sep="")
            print("Gateway:",networkid,"97",sep="")
            print("Broadcast:",networkid,"127",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"97"," - ",networkid,"126",sep="")
            print("--------Network 5--------")
            print("Network id:",networkid,"128",sep="")
            print("Gateway:",networkid,"129",sep="")
            print("Broadcast:",networkid,"159",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"129"," - ",networkid,"158",sep="")
            print("--------Network 6--------")
            print("Network id:",networkid,"160",sep="")
            print("Gateway:",networkid,"161",sep="")
            print("Broadcast:",networkid,"191",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"161"," - ",networkid,"190",sep="")
            print("--------Network 7--------")
            print("Network id:",networkid,"192",sep="")
            print("Gateway:",networkid,"193",sep="")
            print("Broadcast:",networkid,"223",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"193"," - ",networkid,"222",sep="")
            print("--------Network 8--------")
            print("Network id:",networkid,"224",sep="")
            print("Gateway:",networkid,"225",sep="")
            print("Broadcast:",networkid,"255",sep="")
            print("Subnet Mask:",subnet,"224",sep="")
            print("Kullanılabilir ip'ler:",networkid,"225"," - ",networkid,"254",sep="")
            print("_________________________________________________________________________________")

        elif bolum == "16": 
            print("_________________________________________________________________________________")
            print("--------Network 1--------")
            print("Network id:",networkid,"0",sep="")
            print("Gateway:",networkid,"1",sep="")
            print("Broadcast:",networkid,"15",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"1"," - ",networkid,"14",sep="")
            print("--------Network 2--------")
            print("Network id:",networkid,"16",sep="")
            print("Gateway:",networkid,"17",sep="")
            print("Broadcast:",networkid,"31",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"17"," - ",networkid,"30",sep="")
            print("--------Network 3--------")
            print("Network id:",networkid,"32",sep="")
            print("Gateway:",networkid,"33",sep="")
            print("Broadcast:",networkid,"47",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"33"," - ",networkid,"46",sep="")
            print("--------Network 4--------")
            print("Network id:",networkid,"48",sep="")
            print("Gateway:",networkid,"49",sep="")
            print("Broadcast:",networkid,"63",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"49"," - ",networkid,"62",sep="")
            print("--------Network 5--------")
            print("Network id:",networkid,"64",sep="")
            print("Gateway:",networkid,"65",sep="")
            print("Broadcast:",networkid,"79",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"65"," - ",networkid,"78",sep="")
            print("--------Network 6--------")
            print("Network id:",networkid,"80",sep="")
            print("Gateway:",networkid,"81",sep="")
            print("Broadcast:",networkid,"95",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"81"," - ",networkid,"94",sep="")
            print("--------Network 7--------")
            print("Network id:",networkid,"96",sep="")
            print("Gateway:",networkid,"97",sep="")
            print("Broadcast:",networkid,"111",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"97"," - ",networkid,"110",sep="")
            print("--------Network 8--------")
            print("Network id:",networkid,"112",sep="")
            print("Gateway:",networkid,"113",sep="")
            print("Broadcast:",networkid,"127",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"113"," - ",networkid,"126",sep="")
            print("--------Network 9--------")
            print("Network id:",networkid,"128",sep="")
            print("Gateway:",networkid,"129",sep="")
            print("Broadcast:",networkid,"143",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"129"," - ",networkid,"142",sep="")
            print("--------Network 10--------")
            print("Network id:",networkid,"144",sep="")
            print("Gateway:",networkid,"145",sep="")
            print("Broadcast:",networkid,"159",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"145"," - ",networkid,"158",sep="")
            print("--------Network 11--------")
            print("Network id:",networkid,"160",sep="")
            print("Gateway:",networkid,"161",sep="")
            print("Broadcast:",networkid,"175",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"161"," - ",networkid,"174",sep="")
            print("--------Network 12--------")
            print("Network id:",networkid,"176",sep="")
            print("Gateway:",networkid,"177",sep="")
            print("Broadcast:",networkid,"191",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"177"," - ",networkid,"190",sep="")
            print("--------Network 13--------")
            print("Network id:",networkid,"192",sep="")
            print("Gateway:",networkid,"193",sep="")
            print("Broadcast:",networkid,"207",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"193"," - ",networkid,"206",sep="")
            print("--------Network 14--------")
            print("Network id:",networkid,"208",sep="")
            print("Gateway:",networkid,"209",sep="")
            print("Broadcast:",networkid,"223",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"209"," - ",networkid,"222",sep="")
            print("--------Network 15--------")
            print("Network id:",networkid,"224",sep="")
            print("Gateway:",networkid,"225",sep="")
            print("Broadcast:",networkid,"239",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"225"," - ",networkid,"238",sep="")
            print("--------Network 16--------")
            print("Network id:",networkid,"240",sep="")
            print("Gateway:",networkid,"241",sep="")
            print("Broadcast:",networkid,"255",sep="")
            print("Subnet Mask:",subnet,"240",sep="")
            print("Kullanılabilir ip'ler:",networkid,"241"," - ",networkid,"254",sep="")
            print("_________________________________________________________________________________")
        else:
            print("Yanlış subnet değeri girdiniz , lütfen '1,2,4,8,16' değerlerinden birini giriniz.!")
        print("")
        next = input("Yeniden hesaplamak için enter'a basınız, ana menüye dönmek için 'back', çıkmak için 'exit' yazınız.:")
        os.system("cls")
        if next == "":
            continue
        elif next == "back":
            anamenu()
        elif next == "exit":
            os.system("exit")
        else:
            break
anamenu()
